version: 2.1


  command:
    print_pipeline_id: 
    steps:
      - run: 
          command: echo "${CIRCLE_WORKFLOW_ID}" 
         
  jobs:
    my_job:
      docker:
        - image: cimg/base:stable
    steps:
      - run: return 1
      - run:
          name: on error
          command: echo " understand error"        
          when: on_fail
workflows:
  my_workflow:
    jobs:    
      - my_job
      
      