version: 2.1

  commands:
    print_pipeline_id: 
    steps:
      - run: 
          commands: echo "${CIRCLE_WORKFLOW_ID}"
         
  jobs:
    my_job:
      docker:
        - image: cimg/base:stable
    steps:
      - print_pipeline_id:        
  
workflows:
  my_workflow:
    jobs:    
      - my_job
      
      