version: 2.1

jobs:

  save_hello_world_output:
    docker:
      - image: cimg/base:stable 
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo "Hello, World!" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt    
  
  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - run: 
          name: "print my name"          
          command: echo ${My_Real_Name}
      - attach_workspace:
           at: ~/
      - run: cat ~/output.txt         
  
  
workflows:
  my_workflow:
    jobs:    
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      